#!/bin/sh


CORE_LIBS="$CORE_LIBS \
				-lcurl \
				-lmemcached \
				-ljansson \
				-lssl"

CORE_INCS="$CORE_INCS \
					/usr/include \
					/usr/local/include"
						
ngx_addon_name="ngx_http_gluu_ox_module"
HTTP_MODULES="$HTTP_MODULES ngx_http_gluu_ox_module"
NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_gluu_ox_module.c \
								$ngx_addon_dir/ngx_gluu_ox_utils.c \
								$ngx_addon_dir/ngx_gluu_ox_proto.c \
								$ngx_addon_dir/ngx_gluu_ox_memcache.c"

NGX_ADDON_DEPS="$NGX_ADDON_DEPS $ngx_addon_dir/ngx_http_gluu_ox_module.h"